#!/usr/bin/env bash
#
# Adjust default device volume
#
# Dependencies:
#   - libpulse (pactl)
#   - libnotify (notify-send)

VALUE=2
MIN=0
MAX=100

print_help() {
	local script=${0##*/}

	cat <<-EOF
		$script: $script <device> <option> [value]
		    Adjust default device volume

		    Devices:
		      input     Use @DEFAULT_SOURCE@
		      output    Use @DEFAULT_SINK@

		    Options:
		      mute      Toggle mute status
		      up        Increase volume by [value] (default: $VALUE)
		      down      Decrease volume by [value] (default: $VALUE)
	EOF
}

get_status() {
	local muted
	muted=$(pactl "get-${DEVICE_TYPE}-mute" "$DEVICE_NAME" | awk '{print $2}')

	case $muted in
		yes) printf "muted" ;;
		no)  printf "unmuted" ;;
	esac
}

get_volume() {
	pactl "get-${DEVICE_TYPE}-volume" "$DEVICE_NAME" | awk '{print $5}' |
		tr -d "%"
}

get_glyph() {
	case "$DEVICE_TYPE:$1" in
		sink:muted)    printf "󰝟" ;;
		sink:unmuted)  printf "󰕾" ;;
		source:muted)  printf "󰍭" ;;
		source:unmuted) printf "󰍬" ;;
	esac
}

set_volume() {
	local volume=$1

	((volume < MIN)) && volume=$MIN
	((volume > MAX)) && volume=$MAX

	pactl "set-${DEVICE_TYPE}-volume" "$DEVICE_NAME" "${volume}%"

	local status
	status=$(get_status)

	notify-send -a "System" "$(get_glyph "$status") ${device^}: ${volume}%" -u low
		--hint "int:value:${volume}"
}

main() {
	local device=$1
	local option=$2
	local value=${3:-$VALUE}

	if ! [[ $value =~ ^[1-9][0-9]*$ ]]; then
		printf "%s: value must be an integer greater than 0\n" "${0##*/}" >&2
		return 1
	fi

	case $device in
		input)
			DEVICE_TYPE="source"
			DEVICE_NAME="@DEFAULT_SOURCE@"
			;;
		output)
			DEVICE_TYPE="sink"
			DEVICE_NAME="@DEFAULT_SINK@"
			;;
		*)
			print_help >&2
			return 1
			;;
	esac

	case $option in
		mute)
			pactl "set-${DEVICE_TYPE}-mute" "$DEVICE_NAME" toggle

			local status volume
			status=$(get_status)
			volume=$(get_volume)

			notify-send -a "System" "$(get_glyph "$status") ${device^}: ${status^}" -u low
			;;
		up)
			local volume
			volume=$(get_volume)

			set_volume $((volume + value))
			;;
		down)
			local volume
			volume=$(get_volume)

			set_volume $((volume - value))
			;;
		*)
			print_help >&2
			return 1
			;;
	esac
}

main "$@"
