shell /usr/bin/zsh
editor /usr/bin/nvim

# Cursor
shell_integration no-cursor
cursor_shape block

# Opacity
dynamic_background_opacity yes
background_opacity 1
map ctrl+page_up set_background_opacity +0.05
map ctrl+page_down set_background_opacity -0.05
map ctrl+shift+r load_config_file

# Tabs style
tab_bar_style powerline
tab_powerline_style angled
tab_bar_edge top
tab_bar_margin_height 8.0 8.0
window_padding_width 6 13 

# Font  
font_family FiraCode Nerd Font
font_size 10

# Decoration
hide_window_decorations yes 


# BEGIN_KITTY_THEME
# Rosé Pine
include rose-pine.conf
# END_KITTY_THEME
